language: csharp
mono: 5.2.0
dotnet: 2.0.0

install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - dotnet restore

script:
  - dotnet build -c Debug --no-restore -v m
  #- dotnet test Jenkins.Net.Tests/Jenkins.Net.Tests.csproj -c Debug --no-build --filter Category=Unit
  - dotnet pack Jenkins.Net/Jenkins.Net.csproj -c Debug --no-build --no-restore -o bin
  - dotnet publish Jenkins.Net.Console/Jenkins.Net.Console.csproj -c Release -f net45 -o bin -v m --no-restore -p:PublishSingleFile=true

deploy:
  provider: releases
  api_key: $GITHUB_APIKEY
  file:
    - "Jenkins.Net/bin/jenkinsnet.*.nupkg"
    - "Jenkins.Net.Console/bin/Jenkins.Net.Console.exe"
  skip_cleanup: true
  on:
    tags: true
