language: csharp
mono: 5.2.0
dotnet: 2.0.0

install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - dotnet restore

script:
  - dotnet build -c Debug --no-restore -v m
  #- dotnet test Jenkins.Net.Tests/Jenkins.Net.Tests.csproj -c Debug --no-build --filter Category=Unit
  - dotnet pack Jenkins.Net/Jenkins.Net.csproj -c Debug --no-build --no-restore -o bin

deploy:
  skip_cleanup: true
  script:
    - dotnet nuget push Jenkins.Net/bin/Release/Jenkins.Net.*.nupkg --api-key $NUGET_APIKEY
  on:
    branch: master
